# Generated by Django 4.1 on 2022-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_company_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_address',
            field=models.CharField(default=False, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(default='default.png', upload_to='company_logos'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
