# Generated by Django 4.1 on 2022-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_bid_has_paid_bid_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='Amount',
            field=models.IntegerField(default=1000),
        ),
    ]
