# Generated by Django 4.1 on 2022-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
