# Generated by Django 4.1 on 2023-02-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_profile_viewers_trackedprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='viewers',
        ),
    ]
