# Generated by Django 4.1.1 on 2022-09-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(default="Enter your bio here", max_length=1000),
        ),
        migrations.AddField(
            model_name="profile",
            name="tagline",
            field=models.CharField(default="Enter your tagline here", max_length=200),
        ),
    ]
