# Generated by Django 4.1 on 2022-09-28 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_profile_bio_profile_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
