# Generated by Django 4.1.3 on 2022-12-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_delete_review'),
        ('user', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.AddField(
            model_name='review',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='job.bid'),
            preserve_default=False,
        ),
    ]
