# Generated by Django 4.1.3 on 2022-12-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_review_project_review_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='freelancer',
        ),
    ]
