# Generated by Django 4.1 on 2022-12-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_review_project_taskreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Enter your bio here', max_length=1000),
        ),
        migrations.DeleteModel(
            name='TaskReview',
        ),
    ]
