# Generated by Django 4.1.3 on 2022-12-16 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_review_employer_remove_review_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_reviews', to='user.profile'),
        ),
        migrations.AddField(
            model_name='review',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_reviews', to='user.profile'),
        ),
    ]
