# Generated by Django 4.1.3 on 2022-12-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_review_employer_review_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_reviews', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='freelancer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_reviews', to='user.profile'),
        ),
    ]
