# Generated by Django 4.1 on 2023-01-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usernotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='low', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usernotes',
            name='priority',
        ),
        migrations.AddField(
            model_name='usernotes',
            name='Priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.priority'),
        ),
    ]
