# Generated by Django 4.1.3 on 2022-12-16 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_alter_review_employer_alter_review_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
