# Generated by Django 4.1 on 2023-01-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_priority_remove_usernotes_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='usernotes',
            name='author',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.DeleteModel(
            name='UserNotes',
        ),
    ]
