# Generated by Django 4.1.3 on 2022-12-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_delete_review'),
        ('user', '0014_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='job.bid'),
        ),
    ]
