# Generated by Django 4.1 on 2023-01-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_priority_usernotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotes',
            name='author',
        ),
    ]
