# Generated by Django 4.1.3 on 2022-12-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_delete_review'),
        ('user', '0015_alter_review_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='job.bid'),
        ),
        migrations.AlterField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_review', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_review', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='job.job'),
        ),
    ]
