# Generated by Django 4.1 on 2023-02-22 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0017_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewers',
            field=models.ManyToManyField(editable=False, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrackedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
