# Generated by Django 4.1 on 2022-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_category_img_alter_job_years_of_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job',
            name='level_of_education',
        ),
        migrations.RemoveField(
            model_name='job',
            name='maximum_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='minimun_salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
        migrations.RemoveField(
            model_name='job',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='job',
            name='cost',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
