# Generated by Django 4.1 on 2022-09-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_job_city_remove_job_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_address',
        ),
    ]
