# Generated by Django 4.1 on 2022-10-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
