# Generated by Django 4.1 on 2022-12-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ManyToManyField(to='job.category'),
        ),
    ]
