# Generated by Django 4.1 on 2022-12-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
