# Generated by Django 4.1 on 2022-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_remove_job_content_file_jobfile_bidfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfile',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='job_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='BidFile',
        ),
        migrations.DeleteModel(
            name='JobFile',
        ),
    ]
